version: '3.8'

services:
    # API Service
    api:
        container_name: cuidamais-api
        build:
            context: ..
            dockerfile: ./docker/php/Dockerfile
        image: cuidamais-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../src:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - cuidamais-network
        depends_on:
            - db

    # Nginx Service
    nginx:
        container_name: cuidamais-nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - '8000:80'
        volumes:
            - ../src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - cuidamais-network
        depends_on:
            - api

    # PostgreSQL Service
    db:
        container_name: cuidamais-postgres
        image: postgres:15
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: ${DB_DATABASE:-cuidamais}
            POSTGRES_USER: ${DB_USERNAME:-cuidamais}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        networks:
            - cuidamais-network

networks:
    cuidamais-network:
        driver: bridge
